### ISSUE TITLE
C3S_34e Meeting with Ouranos and CRIM: May 2021

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#100]
# Proposed agenda - C3S_34e Meeting with Ouranos and CRIM: 27th May 2021

**1. Minutes and actions from previous meeting**

Previous minutes:  https://github.com/roocs/34e-mngmt/issues/94

**Previous actions**

**2. Project update: c3s_34e [Ag]**

- recent developments:
  - C3S are pleased with our service - they say it is working!
  - almost at the end of first contract; expecting a renewal
  - more work required on CMIP5, CORDEX; average and regrid.
  - moved to intake catalogs as our file inventory
  - working on dynamic `fixes` in `daops` to modify Decadal CMIP6 runs
  - new `usage` process captures usage statistics (Demo)

**3. Project updates: relevant Ouranos/CRIM projects [David/Tom]**

Ouranos:
 
CRIM:

**4. Collaborations and news**

 
**5. Discussion:**

- ESGF Future Architecture progress
- STAC discussions/work
- Regridding:
- Future functionality/plans? 

**6. Agree next steps and next meeting**

 - **Ag to move meetings back to 4-weekly from today - and edit meeting settings in Zoom**
 - Next monthly meeting: Thursday 24th June

**Comment by agstephens** [comment]
- [ ] **Ag to move meetings back to 4-weekly from today - and edit meeting settings in Zoom**

**Comment by agstephens** [comment]
@sol1105 cannot make 24th June, so moved the next meeting back to Thurs 1st July.

**Comment by Zeitsperre** [comment]
I Just realized, but I don't think July 1st will work for Ouranos people (It's :canada: day!)

**Comment by agstephens** [comment]
@Zeitsperre @huard @tomLandry I'm moving the July 1st meeting to the day before (June 30th).
