### ISSUE TITLE
C3S_34e Meeting with Ouranos and CRIM: 30th June 2021

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#101]
# Proposed agenda - C3S_34e Meeting with Ouranos and CRIM: 30th June 2021

**1. Minutes and actions from previous meeting**

Previous minutes:  https://github.com/roocs/34e-mngmt/issues/100

**Previous actions**

- [x] AS: Put regridding higher up the agenda next month
- [x] AS: move meetings back to 4-weekly from today - and edit meeting settings in Zoom
- [x] ES: Create an issue on the xarray repository to explain the `_FillValue` in 1D coordinate variables, and that we believe these contravene the CF-Conventions (See "coordinate variable" section under: https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#terminology). See: https://github.com/pydata/xarray/issues/5448
- [x] MS: Raise an xESMF issue to discuss haloes 

**2. Grids and regridding [Martin]**

- some dedicated time to focus on regridding issues

**3. Project update: c3s_34e [Ag]**

- recent developments:
  - C3S have slightly modified their priorities:
    - subset by list of values (level and time)
    - temporal averages (monthly or annual)
    - CORDEX subsetting
  - still working on dynamic `fixes` in `daops` to modify Decadal CMIP6 runs
  - working on `dashboard` endpoint

**4. Project updates: relevant Ouranos/CRIM projects [David/Tom]**

Ouranos:
 
CRIM:
 
**5. Discussion:**

- STAC discussions/work
- OGC

**6. Agree next steps and next meeting**

**Comment by ellesmith88** [comment]
@agstephens The fill value issue is this one: https://github.com/pydata/xarray/issues/5448, it was closed as a duplicate.

**Comment by sol1105** [comment]
The slides regarding regridding: [Link](https://docs.google.com/presentation/d/1nAX5gpcjAyi8Dkqbmb7U-KGuUn2IQhB7IEJd3RoKNHw/edit?usp=sharing)

Regarding CMIP6 station data requested by CFMIP:
http://clipc-services.ceda.ac.uk/dreq/u/dim:site.html
Would be 2D datasets (time, site/station)
Example: [ESGF http download link](http://vesg.ipsl.upmc.fr/thredds/fileServer/cmip6/CFMIP/IPSL/IPSL-CM6A-LR/amip-4xCO2/r1i1p1f1/CFsubhr/psl/gn/v20180906/psl_CFsubhr_IPSL-CM6A-LR_amip-4xCO2_r1i1p1f1_gn_20090101003000-20150101000000.nc)

**Comment by agstephens** [comment]
# Minutes - C3S_34e Meeting with Ouranos and CRIM: 30th June 2021

**1. Minutes and actions from previous meeting**

Previous minutes:  https://github.com/roocs/34e-mngmt/issues/100

**Previous actions**

- [x] AS: Put regridding higher up the agenda next month
- [x] AS: move meetings back to 4-weekly from today - and edit meeting settings in Zoom
- [ ] ES/AS: Run the cf-checker on example files generated by Xarray to see if 1D coordinate variables with `_FillValue` set will _fail_ cf-checks. Do we need to take action?
- [x] ES: Create an issue on the xarray repository to explain the `_FillValue` in 1D coordinate variables, and that we believe these contravene the CF-Conventions (See "coordinate variable" section under: https://cfconventions.org/Data/cf-conventions/cf-conventions-1.8/cf-conventions.html#terminology). See: https://github.com/pydata/xarray/issues/5448
- [x] MS: Raise an xESMF issue to discuss haloes - **ongoing**

**2. Grids and regridding [Martin]**

MS presented on:
- Out-of-source domain / unmapped grid cells
- Masking - renormalising / adaptive-masking
- Grid halos / ghost cells
- See presentation: https://docs.google.com/presentation/d/1nAX5gpcjAyi8Dkqbmb7U-KGuUn2IQhB7IEJd3RoKNHw/edit#slide=id.p

**3. Project update: c3s_34e [Ag]**

- recent developments:
  - C3S have slightly modified their priorities:
    - subset by list of values (level and time)
    - temporal averages (monthly or annual)
    - CORDEX subsetting
  - still working on dynamic `fixes` in `daops` to modify Decadal CMIP6 runs
  - working on `dashboard` endpoint

**4. Project updates: relevant Ouranos/CRIM projects [David/Tom]**

Ouranos (TL):
- working on intake catalog of NcML datasets (to simplify user view)
- working on reading WFS daily station data into xclim/xarray
 
**5. Discussion:**

- clisops temporal averaging:
  - Temporal averaging - note that `xarray` can resample - but might not create the correct CF metadata. This has been discussed in relation to cf-xarray.
- STAC discussions with CMIP6 Object Store
  - DH: Ouranos will be involved in a proposal to set up CMIP6 object store later this year
  - AS: We are engaging with PANGEO people regarding how this is done in Zarr, we have some experience. Also, we have people working on a STAC solution that will work for ESM (and other) data. 

**6. Agree next steps and next meeting**

Next meeting date: Thursday 29th July.
