### ISSUE TITLE
Set up alternative lookup for elasticsearch content at DKRZ

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#102]
# ElasticSearch supporting roocs

## ElasticSearch cluster

8 server cluster. 
Proxied via nginx: 
 - external IP: elasticsearch.ceda.ac.uk
 - round-robin read access to any of the 8 nodes

## Indexes and aliases

Aliases point to indexes with date-stamped names: "-2021-06-21"

```
[elasticsearch]
endpoint = elasticsearch.ceda.ac.uk
port = 443
character_store = roocs-char         # roocs-c3s-char
fix_store = roocs-fix                # roocs-c3s-fix
analysis_store = roocs-analysis      # roocs-c3s-analysis
fix_proposal_store = roocs-fix-prop  # roocs-c3s-proposals
```

## Permissions and Access

Rules:
- anything starting with "roocs*" is globally visible outside the firewall
- if you have an API key, you can write to any of these inside the firewall (i.e. on sci servers or LOTUS nodes).

Richard can set up a new rule easily.

## Mappings

The mappings for the indexes are _not_ defined by us, and are therefore
analyses/tokenised to be useful for search.

## Cross-site synchronisation of content

Actual synchronisation probably needs to be done manually, so DKRZ could do any of:
- pull the data and write to file-based store, pickle-store, sqlalchemy, postgres, mongo, 
  or other key store
The off-site (i.e. non-CEDA) index does not need to be publicly visible, just available to the DKRZ servers.

## Current elasticsearch usage in `dachar`

Here is the fix store code:
https://github.com/roocs/dachar/blob/master/dachar/fixes/fix_store.py

Tested from:
https://github.com/roocs/dachar/blob/master/tests/test_fixes/test_fix_store.py

And the elasticsearch config looks like:
https://github.com/roocs/roocs-utils/blob/master/roocs_utils/etc/roocs.ini#L133

**Comment by agstephens** [comment]
Plan:
- DKRZ to set up a (Docker) instalment of ElasticSearch locally
- CEDA create a _dump_ of the ES content
- DKRZ to load the content manually
- DKRZ/CEDA to create the ansible recipe to automate the setup
- Share with IPSL

In terms of load-balancing, each node will contact its own ElasticSearch service.

**Comment by cehbrecht** [comment]
ElasticSearch is not used for decadal fixes.
