### ISSUE TITLE
CDS API - basic overview

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#12]
CDS Team would like to see:

```
import esgf_wps

subset = {
    'name': 'subset',
    'arguments': {
        'period': '195001-190012',
        'area': [-10, -10, 10, 10]}
}

average = {
    'name': 'average',
    'arguments': {
         'axes': ['time', 'latitude']}
}

retrieve = {
    'name': 'retrieve',
    'arguments': {
        'ensemble_member': 'r6i1p2',
        'format': 'zip',
        'model': 'giss_e2_h',
        'variable': 'geopotential_height',
        'experiment': 'historical'}
}

request =   

result = esgf_wps.orchestrate(
    'projections-cmip5-monthly-pressure-levels',
   {
    '_service': (average, 
           {'_service': (subset,
               {'_service': (retrieve,  ')}
           }
    },
    'download.zip')
```

Note: Currently we have:

```
import cdsapi

c = cdsapi.Client()

c.retrieve(
    'projections-cmip5-monthly-pressure-levels',
    {
        'ensemble_member': 'r6i1p2',
        'format': 'zip',
        'model': 'giss_e2_h',
        'variable': 'geopotential_height',
        'experiment': 'historical',
        'period': '185001-190012',
    },
    'download.zip')
```

**Comment by agstephens** [comment]
We need to learn from ECMWF about how to push the process tree/list through the WPS interface.

We can still have these processes:
 - subset
 - average
 - regrid

But also:
 - orchestrate - that takes a sequence/tree that resolves to the above in some way.

**Comment by agstephens** [comment]
Need to study the Canadian approach in more detail.

**Comment by agstephens** [comment]
**NOTE: CDS Team are not worried that some users will manage to request process chains that FAIL - just need to respond with meaningful Exceptions.**

**Comment by cehbrecht** [comment]
@agstephens I can prepare a dummy wps with this interface for the next sprint in March for discussion.

**Comment by agstephens** [comment]
@cehbrecht : that would be great. I think we should try to have a very simple set of dummy packages to demonstrate the end-to-end interfaces.

**Comment by agstephens** [comment]
Solution implemented in https://github.com/roocs/rooki
