### ISSUE TITLE
Review all examples we can find of problematic "character"

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#2]
Look into all repositories/tools that capture problems/issues in CMIP5, CORDEX and CMIP6. 

- [x] Record all characteristics in the files/datasets that are responsible for causing errors. 
- [x] Categorise all the errors in terms of the characteristics that we need to record
- [x] Document a list of all characteristics that our characterisation store should record (e.g.: `shape` of main variable)

**Comment by agstephens** [comment]
Please review content of:

https://github.com/ESMValGroup/ESMValCore/tree/master/esmvalcore/cmor/_fixes/cmip5
https://github.com/ESMValGroup/ESMValCore/tree/master/esmvalcore/cmor/_fixes/cmip6

Create a spreadsheet of:
 - types of character/issue/problem
 - related fix (if known)
 - category: global attr, coordinates, variable attribute or data
 - anything else that looks useful

**Comment by ellesmith88** [comment]
Done for ESMValTool - CMIP5 and CMIP6

**Comment by agstephens** [comment]
This work continues in other issues.
