### ISSUE TITLE
Check that `rook` can respond with meta-link for multiple output files

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#33]
As subject.

**Comment by agstephens** [comment]
@cehbrecht please inform James about the proposed functionality to return an Xarray object.

**Comment by agstephens** [comment]
@ellesmith88 : did you find a c3s-cmip5 data set that is bigger than 1Gb?

**Comment by ellesmith88** [comment]
@agstephens No, the biggest I can find is 4.9MB - c3s-cmip5.output1.NOAA-GFDL.GFDL-ESM2M.piControl.day.atmos.day.r1i1p1.va.v20110601

**Comment by agstephens** [comment]
This works perfectly.
