### ISSUE TITLE
Use common logging approach like that in `clisops/__init__.py`

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#40]
See: https://github.com/roocs/daops/blob/master/daops/__init__.py

Can we just import `from clisops import logging`?

**Comment by Zeitsperre** [comment]
> Can we just import `from clisops import logging`?

The logging configuration won't be imported, just the library, no? As far as I can tell, there isn't any special configuration used in clisops so `import logging` and then a very basic initializer would probably be enough. If you want something special, a logging configuration is a bit more complicated (https://docs.python.org/3/library/logging.config.html) but might be worth the effort.

**Comment by agstephens** [comment]
Thanks @Zeitsperre, in `clisops/__init__.py` we have now included:

```
import logging
import logging.config
import os

logging.config.fileConfig(
    os.path.join(os.path.dirname(__file__), "etc", "logging.conf")
)
```

Which uses a basic logging INI file:

https://github.com/roocs/clisops/blob/master/clisops/etc/logging.conf

The intention is that this should provide the basic initialiser.

**Comment by agstephens** [comment]
I have tested this, it can be managed quite simply with:

For `mypackage`:

1. Edit `mypackage/__init__.py` to include:

```
from clisops import logging
```

2. Then anything that needs to log can do:

```
from mypackage import logging

LOGGER = logging.getLogger(__file__)

def do():
    LOGGER.info('hi')

if 1:
    LOGGER.debug('bye')
```

**Comment by agstephens** [comment]
@ellesmith88: I'm assigning this to you, please implement this in `daops` and `dachar` so that all the logging is done the same in the different packages. Thanks
