### ISSUE TITLE
Remove default values in rook subset process

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#42]
We have defaults hard-coded in rook subset process:

https://github.com/roocs/rook/blob/master/rook/processes/wps_subset.py

These need to be removed for `area`, `time` and `level`. You cannot set them to `None` - it breaks the code.

So I think the best fix would be to set the defaults to `''` and then parse them later with:

```
        kwargs = parameterise.parameterise(collection=collection,
                                           time=request.inputs['time'][0].data or None,
                                           level=request.inputs['level'][0].data or None,
                                           area=request.inputs['area'][0].data or None)

```

**Comment by cehbrecht** [comment]
Added a PR for this.

Another question: should we return only one output with the metalink document? The additional `netcdf` output was there only for testing at the beginning.

**Comment by agstephens** [comment]
> Added a PR for this.
> 
> Another question: should we return only one output with the metalink document? The additional `netcdf` output was there only for testing at the beginning.

@cehbrecht : As long as the client can access the contents of the metalink document then I suggest that we just use that. Presumably, you are making `birdy` aware of how to deal with metalink so I'm happy we can use it.
