### ISSUE TITLE
Output dataset gets the wrong name - get_main_variable needs attention

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#49]
http://rook-wps1.ceda.ac.uk/wps?service=WPS&version=1.0.0&request=Execute&identifier=subset&status=true&storeExecuteResponse=true&DataInputs=collection=c3s-cmip5.output1.ICHEC.EC-EARTH.historical.day.atmos.day.r1i1p1.tas.latest;time=1860-01-01/1860-12-30

**Comment by agstephens** [comment]
Please create a unit test for this, using the real archive for the above dataset. 

Check why it is calling the file "lon_bounds....nc" instead of "tas....nc".

**Comment by ellesmith88** [comment]
Quick fix implemented in `roocs-utils`, but needs more investigation to look at why `lon_bounds` is bigger than `tas`

**Comment by ellesmith88** [comment]
Issue is with `result = max(results, key=results.get)` in `roocs_utils/xarray_utils/xarray_utils.py::get_main_variable()`. This returns the "maximum" `var_id` based on a string. It would be sensible to change the creation of the result dict from `results.update({var_id: data.dims})` to something like `results.update({var_id: ds[var_id].size})` so the maximum is found based on the maximum size. This works with a test on real data. (Doesn't work on test_data - due to selection of lat/lon when creating test data?)

Change would be:
```
def get_main_variable(ds):

    data_dims = [data.dims for var_id, data in ds.variables.items()]
    flat_dims = [dim for sublist in data_dims for dim in sublist]

    results = {}
    skips = ["bnd", "bound"]

    for var_id, data in ds.variables.items():

        if var_id in flat_dims:
            continue
        if any(skip in var_id for skip in skips):
            continue
        else:
            results.update({var_id: data.dims})

    result = max(results, key=results.get)

    if result is None:
        raise Exception("Could not determine main variable")
    else:
        return result
```

to 

```
def get_main_variable(ds):

    data_dims = [data.dims for var_id, data in ds.variables.items()]
    flat_dims = [dim for sublist in data_dims for dim in sublist]

    results = {}

    for var_id, data in ds.variables.items():

        if var_id in flat_dims:
            continue
        else:
            results.update({var_id: ds[var_id].size})

    result = max(results, key=results.get)

    if result is None:
        raise Exception("Could not determine main variable")
    else:
        return result
```

**Comment by agstephens** [comment]
@ellesmith88: great that you have found a fix. A pain that it won't work properly with the test data. 

Maybe we can say that we _never_ expect "lat", "latitude", "lon", "time", "lon_bounds" etc to be the main variable and we exclude them. And maybe we change it to:

`def get_main_variable(ds, exclude_common_coords=True):`

- so you can force it to ignore the exclusions in special cases.
