### ISSUE TITLE
Add some tasks

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#57]
- [x] Review plan in Google doc
- [x] Set up ...

**Comment by sol1105** [comment]
I worked a little on the Review in our [34e-Grids Google Doc](https://docs.google.com/document/d/1A8VQdolfvr5Yv8ijAgFkkFq07cB8Mgta_bZxGgkghzY/edit#), included some References and worked on the Roadmap. Some points are up for discussion (maybe suitable for the next 34e group meeting on fridays).
