### ISSUE TITLE
Create c3s-cmip6 inventory and deliver to ECMWF

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#58]
Capturing this in an issue.

**Comment by agstephens** [comment]
@ellesmith88  We should use these manifests (file lists) to create our dataset list for the inventory.

https://github.com/cp4cds/c3s_34g_manifests/blob/master/cmip6_3d/manifest_c3s-34g_cmip6_r1_3d_latest.txt
https://github.com/cp4cds/c3s_34g_manifests/blob/master/cmip6_2d/manifest_c3s-34g_cmip6-r1_2d_latest.txt

**Comment by ellesmith88** [comment]
@agstephens This is running well for these datasets and has almost finished (had to run again after the weekend). In the inventory we take the min and max of the coords, but in a few datasets there are coordinates that aren't numbers. 
e.g. in the dataset `CMIP6.ScenarioMIP.IPSL.IPSL-CM6A-LR.ssp245.r1i1p1f1.Lmon.landCoverFrac.gr.v20190119` there is a coordinate called `sector` with dim `type` which has values:
```
>>> ds.sector.values
array([b'bare_ground', b'tropical_broad_leaved_evergreen',
       b'tropical_broad_leaved_raingreen',
       b'temperate_needleleaf_evergreen',
       b'temperate_broad_leaved_evergreen',
       b'temperate_broad_leaved_summergreen',
       b'boreal_needleleaf_evergreen', b'boreal_broad_leaved_summergreen',
       b'boreal_needleleaf_summergreen', b'temperate_C3_grass',
       b'C4_grass', b'C3_agriculture', b'C4_agriculture',
       b'tropical_C3_grass', b'boreal_C3_grass'], dtype='|S255')
```

How should this be represented in the inventory - if at all? Maybe rather than the min and mix the inventory could show how many different types there are?

**Comment by agstephens** [comment]
@ellesmith88, this is an interesting case. Here is the `ncdump` for the variables section, with only the relevant stuff kept in:

```
variables:
        float lat(lat) ;
...
        float lon(lon) ;
...
        char sector(type, str_len) ;
                sector:name = "sector" ;
                sector:standard_name = "model_level_number" ;
                sector:long_name = "Vegetation or Land Cover Type" ;
                sector:units = "1" ;
        double time(time) ;
...
        double time_bounds(time, axis_nbounds) ;
        float landCoverFrac(time, type, lat, lon) ;
...
                landCoverFrac:coordinates = "sector" ;
```

What I find interesting is that `roocs_utils` is identifying `sector` as a `level`.

I have just tried it (with what might be an out of date version of `roocs_utils`), and it didn't identify `sector` as level:

```
>>> from roocs_utils.xarray_utils.xarray_utils import is_level
>>> import xarray as xr
>>> ds = xr.open_dataset('/badc/cmip6/data/CMIP6/ScenarioMIP/IPSL/IPSL-CM6A-LR/ssp245/r1i1p1f1/Lmon/landCoverFrac/gr/v20190119/landCoverFrac_Lmon_IPSL-CM6A-LR_ssp245_r1i1p1f1_gr_201501-210012.nc')
>>> is_level(ds.sector)
False
```

Do you get a different result with the most up-to-date `roocs_utils`?

**Comment by ellesmith88** [comment]
@agstephens With the most up to date version it is identified as level

```
>>> import xarray as xr
>>> from roocs_utils.xarray_utils.xarray_utils import is_level
>>> ds = xr.open_mfdataset("/badc/cmip6/data/CMIP6/ScenarioMIP/IPSL/IPSL-CM6A-LR/ssp245/r1i1p1f1/Lmon/landCoverFrac/gr/v20190119/*.nc", use_cftime=True, combine="by_coords")
>>> is_level(ds.sector)
True
```

So the change that Pascal made for us - changing from `cfunits` to `cf_xarray` must have had an impact. This is the function now:

```
def is_level(coord):
    """
    Determines if a coordinate is level.

    :param coord: coordinate of xarray dataset e.g. coord = ds.coords[coord_id]
    :return: (bool) True if the coordinate is level.
    """
    if "vertical" in coord.cf and coord.cf["vertical"].name == coord.name:
        return True

    if hasattr(coord, "positive"):
        if coord.attrs.get("positive", None) == "up" or "down":
            return True

    if hasattr(coord, "axis"):
        if coord.attrs.get("axis", None) == "Z":
            return True

    return False
```

So it must be the first if statement that is identifying it as level

**Comment by agstephens** [comment]
Hi @ellesmith88, it looks like the `coord.cf` option is making a decision that we might not agree with. However, I reckon our best option is to workaround the problem by saying that we DO NOT support subsetting on text-based coordinates in daops/clisops.

So, you could maybe test if the `type` of the first value is either a string or bytes value, and base the decision on that. E.g.:

```
v0 = coords.values[0]
if isinstance(v0, str) or isinstance(v0, bytes):
     ...do not treat it as a real coordinate...
```

For now, you can embed this in the inventory code - to get something to James.

But please also create an issue describing this real world example and tag Carsten and the clisops folks. It would be good to get their opinion on whether they want `roocs_utils` to treat a text coordinate as a `level`. Thanks

**Comment by ellesmith88** [comment]
@agstephens Ok great - thanks for taking a look!

I have already sent the incomplete version to James - this is just to get the final 2 datasets :-)

**Comment by agstephens** [comment]
Done
