### ISSUE TITLE
Create "notebooks" directory in each repo

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#63]
@ellesmith88 @cehbrecht I think we should follow the `rook` example and have a `notebooks` directory at the top-level of each of our main repositories. This can be used to demonstrate the core functionality and we can also create a symlink back to it in our `docs` directory and use it as part of the documentation generated by `sphinx`/`nbsphinx`.

The exception is `rook`.

**Comment by agstephens** [comment]
Hi @ellesmith88, can we close this one now?

**Comment by ellesmith88** [comment]
Yes - `rooki`, `daops`, `clisops`, `dachar` and `roocs-utils` all have a notebooks directory.
