### ISSUE TITLE
Work out how to interact with inventories in order to convert a WPS request to a list of file URLs

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#66]
# Proposal for how the WPS will act as a proxy to files under the data node

## Req 0: For this task, our inventory must include files (as well as datasets)

- [x] Add files to the inventory script.

If we are mapping datasets to files then we need information about the individual files and their datetime ranges.

## Req 1: Generate an inventory for each project (initially CMIP6)

- [x] Generate a CMIP6 C3S inventory

Write the inventory in a format used by the "rook" WPS and by ECMWF. Start with YAML format. Generate it from the latest manifest of QC'd data:

https://github.com/cp4cds/c3s_34g_manifests

## Req 2: The WPS should PREVENT access to non-QC'd data

- [x] Implement a gatekeeper function based on the inventories for C3S

The WPS should only provide access to data that has been provided for C3S. Therefore, all requests must check against a manifest/inventory before deciding which files to process/point to.

We should return an HTTP "403 Forbidden" response.

This should happen within a module called by `rook`.

##  Req 3: Translate the inputs into the required actions

NOTE: the code needs to work out if whole files **or** WPS output files are required.

**NOTE: we should NOT provide a mixture of WPS-derived files and ESGF Node whole files because they *might* not aggregate together.**

If no spatial or level subsetting, or averaging, or regridding, is requested: return whole files.
If user selects "whole files only": return whole files

- [x] Work out if whole files are required.

If we _can_ return whole files from the WPS, then just collate the file URLs and return in the MetaLink response.

If the cases above do not apply: return WPS-generated files.

- [x] Work out if WPS-generated files are required.

Generate these and then return the file URLs in the MetaLink response.

**Comment by agstephens** [comment]
@ellesmith88: please come up with some ideas for how these interactions might be managed.

**Comment by ellesmith88** [comment]
@agstephens @cehbrecht I've created a flowchart here https://drive.google.com/file/d/1-NCtTZ9NdobNt8PbeMNJ8TSllmp6Ywfu/view?usp=sharing for how we decide whether to return WPS generated files or file URLs. You should be able to edit it as well. 

Do you think WPS files should be returned if `is_characterised` is selected but `apply_fixes` isn't or `apply_fixes` is but there are no fixes? I.e. the part of the flow chart where the 2 'no' options join together, or does this imply that the original files would be ok? (because they are characterised but no fixes need to be applied)

Currently I have assumed this applies that the whole files would be ok as long as no subsetting is selected but this may not be the case!

**Comment by ellesmith88** [comment]
Also a UML diagram I had a go at: https://drive.google.com/file/d/19RL7kEGTWs_WwpIKNQy-27gIjfir8tis/view?usp=sharing

**Comment by cehbrecht** [comment]
I'm also getting a bit confused when to return whole "original" files. 

We can return "original" files only for time subsetting? In case of cordex there could also be a bbox selection?

Should there be an additional option `original_files_only` for subsetting?

When `apply_fixes` is true then I would expect processed files ... not sure if we should check if fixes are available.

To remove my confusion it would be easier if we would have an additional operator `select(time, bbox)` which always returns original files filtered by the given parameters.

For all other operators I would expect processed files.

**Comment by agstephens** [comment]
Hi @cehbrecht, some responses:

We can return "original" files only for time subsetting? In case of cordex there could also be a bbox selection?
> The CORDEX case is interesting. You are right that a box could match a CORDEX domain exactly. So maybe we need to build a general _checker_.

Should there be an additional option original_files_only for subsetting?
> @ellesmith88 and I discussed that the `original_files_only` option only works when the user does not make certain selections, so we think it can be omitted.

When apply_fixes is true then I would expect processed files ... not sure if we should check if fixes are available.
> We think that we need to check if there are fixes because that will force the use of the WPS, whereas if there are no fixes to apply then it may be possible to provide the original ESGF files.

**Comment by agstephens** [comment]
@ellesmith88 @cehbrecht  just confirming that we agreed to include an extra boolean parameter for `rook` called: `original_files`. The default value is `False`. If this is set to `True` then we ignore any subset options and ignore the `apply_fixes` flag.

**Comment by ellesmith88** [comment]
> @ellesmith88 @cehbrecht just confirming that we agreed to include an extra boolean parameter for `rook` called: `original_files`. The default value is `False`. If this is set to `True` then we ignore any subset options and ignore the `apply_fixes` flag.

Yes - this is updated on the flowchart now

**Comment by agstephens** [comment]
@ellesmith88 I have had a good go at this issue. I have written lots of code without any tests...which will be interesting. 

I moved the code into the following location in rook:

  https://github.com/roocs/rook/tree/director/rook/director

What I would like us to do on Monday is to see if we can make it (pseudo-) operational. 

Please take a look at the "director" branch and check it out on your system. 

The new code gets called from inside:

 https://github.com/roocs/rook/blob/director/rook/processes/wps_subset.py#L118

It calls out to the `Director` class which encapsulates the different checks from your workflow diagram.

The `Director` out-sources some of the logic to the `Inventory` class which in turn reads its inventories from the `InventoryCache` class.

Finally, the `Director` uses the `SubsetAlignmentChecker` class to work out if the datasets within a collection happen to coincide with the time interval requested by the user.

Note that this has some completely unimplemented code:

 https://github.com/roocs/rook/blob/director/rook/director/alignment.py#L21-L34

These two methods (and any other supporting methods/functions they might depend upon) would be a good place for you to add some code, and then we can converge by writing tests for different components and gradually bringing it into operation.

**Comment by agstephens** [comment]
Closing as this has been implemented. We will deal with future changes in other issues.
