### ISSUE TITLE
Decide on a common approach for documentation between roocs packages

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#69]
For example: CONTRIBUTIONS docs
 - should all be consistent.

**Comment by Zeitsperre** [comment]
If i could suggest something, it would be to use the NumPy conventions for docstrings (https://numpydoc.readthedocs.io/en/latest/format.html). I find them to be much more readable than other options.

**Comment by agstephens** [comment]
Thanks @Zeitsperre , that looks useful.
