### ISSUE TITLE
Meeting with Ouranos: Nov 2020

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#71]
# Proposed agenda for meeting - 04/11/2020

**1. Minutes and actions from previous meeting**

Previous minutes:  https://github.com/roocs/34e-mngmt/issues/59

Previous actions:

- [x] AS: set up a monthly meeting in this Thursday slot.
- [x] AS: to discuss code management procedures with the 34e team
- [x] TJS: Add a Pull Request template for CLISOPS: https://github.com/roocs/clisops/issues/70
- [x] AS: liaise with team to get a new release published this month - _in progress_
- [ ] AS: discuss with 34e team how we add support for static typing: https://github.com/roocs/clisops/pull/67 - _in progress_
- [x] AS: put a "what we have learnt about dask" item on the next meeting agenda

**2. Project update: c3s_34e [Ag]**

**3. Project updates: relevant Ouranos/CRIM projects [David/Tom?]**
  - of particular interest to 34e:
    - latest status of regridding work
    - latest status of NcML work

**4. c3s_34e experience with Dask [Ag/Elle]**
  - what we have learnt about dask

 **5. Discussion:**

  - clisops plans and recent issues:
    - pending release
    - release procedure - can we converge
    - managing test datasets (for unit tests, in multiple repositories)
  - xESMF and regridding issues
  - other activities

 **6. Agree next steps and next meeting**

**Comment by cehbrecht** [comment]
@fmigneault As mentioned in our meeting you wanted to try our [rook WPS](https://github.com/roocs/rook) with weaver. Can you use the load-balanced url:

http://compute.mips.copernicus-climate.eu/wps?service=WPS&version=1.0.0&request=GetCapabilities

You can see the availability of the compute service in the GeoHealthCheck:
https://geohealthcheck.cloud.dkrz.de/resources?lang=en&tag=compute

There are example notebooks with http requests and [rooki/birdy](https://github.com/roocs/rooki) using the rook WPS:
https://nbviewer.jupyter.org/github/roocs/rooki/tree/master/notebooks/demo/

Currently the demo service is using a very limit set of demo data:
https://github.com/roocs/mini-esgf-data

**Comment by fmigneault** [comment]
@cehbrecht 
I did not test the execution of processes yet, but deployment of the provider worked: 
https://ogc-ades.crim.ca/ADES/providers/copernicus-rook

All path under this are as per OGC-API Processes
eg: REST "GetCapabilities" is https://ogc-ades.crim.ca/ADES/providers/copernicus-rook/processes and so on

The displayed information are dynamic, in the sense that 
https://ogc-ades.crim.ca/ADES/providers/copernicus-rook/processes/subset 
will call the corresponding "DescribeProcess" request on the rook WPS and generate the fields on the fly by converting the response to REST OGC API - Processes format.

**Comment by agstephens** [comment]
@fmigneault the JSON outputs are looking so much easier to read compared to old WPS XML docs. Nice! Thanks
