### ISSUE TITLE
Old version of datasets in inventory but they don't exist on file system anymore

### ISSUE THREAD

**Issue by ellesmith88** [roocs/34e-mngmt#84]
In the inventory at the moment there are three datasets (there might be more) that don't exist on the file system anymore.

These are 
c3s-cmip6.CMIP.NCC.NorCPM1.historical.r1i1p1f1.day.tas.gn.v20191005
c3s-cmip6.CMIP.NCC.NorCPM1.historical.r1i1p1f1.day.tasmin.gn.v20191005
c3s-cmip6.CMIP.NCC.NorCPM1.historical.r1i1p1f1.day.pr.gn.v20191005

Only the newer version v20200724 is available

**Comment by agstephens** [comment]
@ellesmith88 please check if this is still an issue with our new inventory.

**Comment by ellesmith88** [comment]
The latest version of the inventory, v20210311, does not contain these datasets
