### ISSUE TITLE
Update test data management on all repos

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#85]
Make the following changes to our test-data solution in:

- roocs-utils
- clisops
- daops
- rook

## Change 1: Replace use of `os.system` for updating the repository

- [ ] Add package to `requirements_dev.txt`: https://gitpython.readthedocs.io/
- [ ] Replace the code to clone the repository, to use the `gitpython` module instead of `os.system`

## Change 2: Use an environment variable to decide whether to update the test-data

In the `load_esgf_test_data()` fixture function (in: `tests/conftest.py`): 
- [x] if test data repo has not been cloned: gitpython clone repo
- [x] elif `os.environ.get('ROOCS_AUTO_UPDATE_TEST_DATA', True) == 'FALSE'`:  do not update the repo(s)
- [x] else: do update the repo (gitpython pull) 

So the user can explicitly switch OFF the automatic `git pull` - but it happens by default in any standard run of the tests.

Linked to: https://github.com/roocs/clisops/issues/121

**Comment by jhaigh0** [comment]
Cloning
```
from git import Repo
Repo.clone_from(git_url, repo_dir)
```

Pulling
```
from git import Repo
repo = Repo(repo_dir)
repo.remotes[0].pull()
```
