### ISSUE TITLE
Can we do any load-testing before launch?

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#91]
@cehbrecht Can you think of any simple way we can do some load-testing before launch?

E.g.:
- Submit 500 requests in 10 seconds - do they all get received, queued and processed successfully?
- Submit 500 requests in 10 minutes - do they all get received, queued and processed successfully?

**Comment by cehbrecht** [comment]
I looked already at: https://locust.io/ 

Looks easy ... and my test server survived the tests 😄  

We can add a test-suite for this to rook ...

**Comment by cehbrecht** [comment]
I can add a `locust` test to rook this week ... we can improve it later. But should be fine for an initial test run.

**Comment by agstephens** [comment]
Hi @cehbrecht, what results did you get from the locust test?

**Comment by cehbrecht** [comment]
I have defined locust tests:
https://github.com/roocs/rook/tree/master/tests/storm

Run:
```
locust -f tests/storm/locustfile.py
```

And select the rook server to test in the web interface:
http://0.0.0.0:8089

The old VM (8CPUs, 16GB) could barely hold one 1 user. The new one (32CPUs, 128GB) survives 5-10 concurrent users.
