### ISSUE TITLE
Prototype using intake for inventory file

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#93]
Issues:
- [x] `intake` or `intake-esm`?
- [x] include file sizes as well as start/end datetimes
- [x] other content needed/useful?
- [x] think about whether `daops.consolidate` could use intake catalogs as an alternative to opening the files to get the years

**Comment by cehbrecht** [comment]
@ellesmith88 something to play with:
* intake home: https://intake.readthedocs.io/en/latest/
* a "pure" intake catalog generated from our inventory: https://github.com/cp4cds/c3s_34g_manifests/tree/master/intake
* intake esm plugin: https://intake-esm.readthedocs.io/en/latest/

intake-esm is used by pangeo and also for local catalogs (at DKRZ, with local file paths):
* https://pangeo-data.github.io/pangeo-cmip6-cloud/accessing_data.html#preprocessing-the-cmip6-datasets
* https://intake-esm.readthedocs.io/en/latest/supplemental-guide/faq.html#is-there-a-list-of-existing-catalogs

**Comment by ellesmith88** [comment]
@cehbrecht great thank you, I'll start having a look

**Comment by ellesmith88** [comment]
@cehbrecht I just got around to having a look at this.

I can't see that it would make any difference to us whether we use intake or intake-esm, except that we would have to 
change https://github.com/cp4cds/c3s_34g_manifests/blob/master/intake/catalogs/c3s.yaml what do you think?

So what we want is to have a way of generating the catalog from the dataset ids - replacing https://github.com/roocs/roocs-utils/tree/master/roocs_utils/inventory, and then as a separate issue look at `daops.consolidate`,  is that right?

**Comment by ellesmith88** [comment]
If we want to use the catalog in `daops`, do you think this https://github.com/roocs/rook/tree/master/rook/catalog should be moved to `roocs-utils`?

**Comment by agstephens** [comment]
@ellesmith88 yes, I was thinking it would end up migrating to `roocs-utils`

**Comment by cehbrecht** [comment]
> I can't see that it would make any difference to us whether we use intake or intake-esm, except that we would have to
> change https://github.com/cp4cds/c3s_34g_manifests/blob/master/intake/catalogs/c3s.yaml what do you think?

For us, it does not matter. Personally I would start with a "normal" intake one. But hopefully in future we can re-use the catalogs for other projects. But maybe it is easier to think about it in another iteration ... we would already be prepared.

**Comment by cehbrecht** [comment]
> If we want to use the catalog in `daops`, do you think this https://github.com/roocs/rook/tree/master/rook/catalog should be moved to `roocs-utils`?

We need to query the catalog before we do any operation ... either provided by rook or daops. Currently I'm "misusing"  out pywps database for the quick-lookup of the catalog (so, part of rook).  In addition we need the catalog builder which is independent of out deployment. So would have the "search" part in rook/daops and the "builder" maybe in the intake catalog repo. I would not "overload" roocs-utils.

**Comment by ellesmith88** [comment]
> We need to query the catalog before we do any operation ... either provided by rook or daops. Currently I'm "misusing" out pywps database for the quick-lookup of the catalog (so, part of rook). In addition we need the catalog builder which is independent of our deployment. So would have the "search" part in rook/daops and the "builder" maybe in the intake catalog repo. I would not "overload" roocs-utils.

Ok so the "builder" needs to have new repo rather than live in roocs-utils like the current inventory maker. The search part should at least move to daops so we can use it there.

I started having a look at how to use an intake catalog with `daops.consolidate` on branch `issue/62/intake_for_consolidate` but haven't got very far.
